### ISSUE TITLE
Wish -- Search without replacement, but with return code instead

### ISSUE THREAD

**Issue by O-D-S** [msztolcman/subst#3] opened 2017-09-09 11:29 UTC
Dear Marcin,

I would like to use subst.py for replacements in the output of TTX ([fonttools](https://github.com/fonttools/fonttools)). For this purpose I need a Python find and replace script like yours, with the help of which I can check, if a string exists, before I replace anything, because I want to replace another string, if the first string does not exist. Unfortunately you also have to specify a replacement, if you specify a pattern. But in some cases, I would like to specify the pattern only and check a return code – an errorlevel or a keyword like "found" or "notfound".

Your script is almost exactly, what I was searching for. Except from the bug, that I have reported. And except from the need to specify both, pattern and replacement.

**Comment by msztolcman** [comment] 2017-09-10 08:57
Hi O-D-S, I'm glad you find it `subst` useful :)

If I understand correctly, you want to use `subst` for searching for pattern, like unix `grep` tool with `-q` param. In general, `subst` is a tool for replacing patterns - it's why replacement is required. But you're right, it can be very useful. In fact, you reported 2 tasks:
- return code of subst could return some informations (ie. 0 - there was any replacements, 1 - wasn't etc)
- ability to search only for patterns

I will think on it today, and maybe try to implement something. But can't promise solution for today :)

Thanks for your ideas!

**Comment by O-D-S** [comment] 2017-09-10 11:53
I think, it is better, if I give an example:

This is the decompiled name table of an OpenType font. (I have removed all namerecords except from three.):

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.13">

  <name>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Example Std Bold
    </namerecord>
    
    [more namerecords]
    
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Example Std
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Bold
    </namerecord>
  </name>

</ttFont>
```

Because there may be many namerecords for MacOs and for Windows, I want to comment this decompiled name table with the help of a search and replace script. But the namerecords with the name IDs 16 and 17 are not necessarily contained in the name table, although they would be useful. So I want to check, if these two namerecords are contained in the name table. And I would like to check that with the help of your script. If the two namerecords are there, my batch script shall comment them with the help of your script in a second step. The output would be:

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.13">

  <name>
<!-- MS-1-!!! / MNC 30. (Furthermore remind the width of the font-menu in MS-apps.) / MS Sub Family (which can have four members at the most) / Examples: Mother Semibold -->
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Example Std Bold
    </namerecord>

    [more namerecords]

<!-- MS-16-(!!!) / Preferred Family (Mother Family) / Omitted, if identical to MS-1 (MS Sub Family). -->
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Example Std
    </namerecord>
<!-- MS-17-(!!!) / Preferred Sub Family (Long Style) / Omitted, if identical to MS-2 (Short Style, member of MS Sub Family). -->
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Bold
    </namerecord>
  </name>
</ttFont>
```

If the two namerecords are **not** there, my batch script shall **add** them (empty and as comment) with the help of your script in a second step. The output would be:

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.13">

  <name>
<!-- MS-1-!!! / MNC 30. (Furthermore remind the width of the font-menu in MS-apps.) / MS Sub Family (which can have four members at the most) / Examples: Mother Semibold -->
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Example Std Bold
    </namerecord>

    [more namerecords]

<!-- Check, if required / MS-16 / Preferred Family (Mother Family) / Omitted, if identical to MS-1 (MS Sub Family).
<namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
</namerecord>
-->
<!-- Check, if required / MS-17 / Preferred Sub Family (Long Style) / Omitted, if identical to MS-2 (Short Style, member of MS Sub Family).
<namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
</namerecord>
-->
  </name>

</ttFont>
```

Ideally the return code for a command "search only" would be the number of occurences of the pattern. Then I could check, if it is >0. But for my purposes it would be enough, if the return code would only be differentiate between Yes and No (or 0 and 1 at the minimum).

And I would like to use your script for "search only" and "for search and replace", because otherwise I had to use a command in my batch script, which is not necessarily available on Linux or on the Mac, but only on Windows. If I publish the batch script, Linux or Mac users could easier adjust it for their operating systems.

And why do I want to use a Python script, but not Perl for example?: Because the Fonttools require Python. So it is already there and the users don't have to download and install Perl or Sed or whatever. I want to make it as comfortable as possible for them, because for many people, that are interested in fonts, inclusively professional type designers/developers, the Fonttools are so complicated to use, that they waste their money for expensive commercial software like the OTMaster (Dutch Type Library), that is less powerful than the Fonttools / the AFDKO (Adobe Font Development Kit for Opentype), that includes the Fonttools.

Sorry for the long text. I am simply excited, that I have found your script. And I cannot emphasise strongly enough, how useful it is in my opinion.

**Comment by msztolcman** [comment] 2017-09-10 14:24
Thanks for wide explanation, it helps a lot :) As I said, I will think on it today :) However, `subst` can help you with your task, even without further changes (but I know with them it would be simpler, though :) ).

1. To add records to the .xml file, you can also use `subst` - just use pattern like:

   ` s!</name>!<info about namerecords you want to add></name>!`

or sth similar :)
It will change closing tag `</name>` with the same, but with some content before it :)

2. To verify if some pattern exists, you can add param `--verbose` and parse it's output (I know, it's not easily parsed, but it's doable). And to not change anything in file, you can replace what you find with same content, ie.:

    `s/(nameID="16")/\1/`

So, if you call `subst` like:

    subst --verbose -s 's/(nameID="16")/\1/' /tmp/a.xml

You will receive output:

    /tmp/a.xml
        1 replacements

if string `nameID="16"` exists in file (if not, there will be answer `0 replacements`).

**Comment by O-D-S** [comment] 2017-09-10 21:43
>     To add records to the .xml file, you can also use subst - just use pattern like:
> 
>     s!</name>!<info about namerecords you want to add></name>!

Yes, I know. That’s the way I have added the info with the help of [rxrepl.exe](https://sites.google.com/site/regexreplace/). (Rxrepl also misses search only functionality.)

> You will receive output:
> 
> /tmp/a.xml
>     1 replacements

Thanks! For the case, that you don't modify the script, that the -r-option can be omitted (search only functionality), I will search that way.

**Comment by msztolcman** [comment] 2017-09-11 21:47
Hi O-D-S,

I was thinking on it a little. And in my opinion adding search-only feature has no sense here. First, `subst` is for *replacing* pattern with some replacement. Second -`subst` by design works on multiple files. Replacing pattern in many files is in my opinion something very different then searching for some pattern. In first case - result is changed file (and by default copy of original file), in second - *just displaying a list of files/paths that contains this pattern*. I hope you understand why I don't want to implement this idea :)

You mentioned also that you want tool written in Python because of other stuff. I can recommend you other tool (written also in Python), designed to *searching* for patterns. Please look at [pss tool](https://github.com/eliben/pss). 

However, second part, about exit code is very good, and I think it should be implemented by me from the beginning ;) I have some implementation prepared, but I need few days for polishing, and then I will release new version.

**Comment by O-D-S** [comment] 2017-09-11 23:21
> in second - just displaying a list of files/paths that contains this pattern.

I am not sure, if I understand the difference. In my imagination a replacement is basically an extension of a pure search. More to the point: You can only replace anything, if you have found it. And in most cases you have to search for the thinks, that you want to find.

As far as I understand, you can either specify a directory or a file in the subst.py command. If subst.py had search only functionality, it indeed would be useful, if subst.py would output a list of the files along with the number of matches for each file. This would be a clean solution. Alternatively it simply could output the total number of discoveries without the places of discovery (pathes / file names). This alternative solution would not be clean, if you specify a path to a directory in the subst.py command, but not a path to a file. But because I am putting the subst.py command in a for loop, it would not matter:

```
for %%f in (Decompile\*.*) do (
python.exe subst.py -p ALPHA -r BETA "DecompileD\%%~nf.ttx"
)
```

Thanks for the link to the pss tool! But you have written in an earlier post, that I could use the verbose argument for a pure search. Although I will have a look at the pss tool, I think, I prefer the solution with the verbose argument for the check, if the pattern is present in the input file. I have not yet tested that, because I think, it is better to wait with my tests, until you have fixed the bug, that causes the error 32 on Windows. I had found some threads on stackoverflow regarding to Python and the error 32, but I was not able to fix the bug.

Good night!

**Comment by msztolcman** [comment] 2017-09-17 15:41
Hi O-D-S, sorry for late answer, but I've got sick and needed to cure :)

> you replace a pattern in the Windows file "hosts"

`/etc/hosts` is unix path ;) But it doesn't matter, on Windows it's same name but in different location ;)

> I don't understand the problem with the search-only-functionality at all

Different usecases. Maybe I can't explain it enough, but currently everything in `subst` is build about editing files and replacing patterns, and search-only functionality is in a little other place. I will think on it more, but now I leave it in current form. I am working mostly with unix-like environments, and for me searching for patterns is task for `grep` utility (that is by default in every unix I ever met ;) ). Of course it doesn't explain why I don't want to put this in subst, but it explains why subst was built around replacing instead of searching :)

From the other side, I've implemented returning error-codes (but currently only "booleans" - 1 - was any replacement, 0 - nothing was changed). Why not a number of replacements? Because in unix (posix) I can't return error-code bigger then 255... :)

**Comment by O-D-S** [comment] 2017-09-17 19:33
This:

> I've implemented returning error-codes (but currently only "booleans" - 1 - was any replacement, 0 - nothing was changed)

is in combination with the following command in my batch file

`python.exe subst.py --stdout --encoding-file utf8 --count 1 --verbose -p "search string" -r "" Testfile.txt >NUL`

almost as good as a command without -r (replacement).

It only looks less esthetic than this (which does not work, because a replacement actually is required). :)

`python.exe subst.py --encoding-file utf8 --count 1 --verbose -p "search string" Testfile.txt`

Except from the aesthetics a pure search is maybe faster, because it would not require the generation of a temporary file. But there I am not sure.

But with regard to my personal utilization of subst.py I meanwhile think, that a search only functionality would not have an advantage for me, because actually I only have these two kind of cases:

1.  I want to replace "alpha" with "gamma", but if "alpha" does not exist, I want to replace "beta" with "delta". So it would not make sense, to start a pure search for alpha or beta.

2. I want to replace "epsilon" with "zeta", but if "epsilon" does not exist, I don't want to replace another string.

However, I don't write this post to persuade you. It was only for clarification. I am not a programmer and my English is not good.

**Closed** 2017-09-18 10:16 UTC

**Comment by msztolcman** [comment] 2017-09-18 10:18
This issue is already resolved in master branch, but not fully tested yet. It would be great if you can test it on Windows, if all your usages will work as expected, then I will release new version of `subst` with all these fixes. Thanks!

**Comment by O-D-S** [comment] 2017-09-18 15:49
The exit code works.

**Comment by msztolcman** [comment] 2017-09-18 16:06
Great! Thank you :)
